### ISSUE TITLE
If the GRIB2 format is a random accessible format, the ability to retrieve a partial set of data would be desirable

### ISSUE THREAD

**Issue by satakagi** [BlueNetCat/grib22json#1]
There is [an implementation](https://github.com/greggman/unzipit) that allows random access to zip archive files using [http range requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests).

If the GRIB2 format allows random access to some of the data (sorry, I have no knowledge of whether this is possible or not. If it is not possible, please close this suggestion), it would be very practical to be able to read individual data ( layer) in a large GRIB2 file with a http range request.

**Comment by gerardllorach** [comment]
Hi @satakagi I think this is outside the scope of the grib2 decoder so I am not going to implement it.

From what I know, it is possible to do what you mention (read individual data ( layer) in a large GRIB2 file with a http range request). GRIB2 is in binary format and each section has a header specifing the length in bytes of each section. You could request specific parts of the GRIB2 to find out where is the data that you need. As the GRIB2 is in binary and each section describes how many bytes it takes, you can jump from section to section by only requesting and reading the headers. You can use the code in the repository to decoded each section individually.
